
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '-\xdd\x04\xf0\xd4j}T\xc4\xe6\x08c\x0bg\xc8\xfc'
    
_lr_action_items = {'RPAREN':([1,3,4,6,8,9,10,11,12,],[-6,-3,-5,-4,-2,11,-7,-1,-8,]),'STRING':([0,1,2,3,4,5,6,8,9,10,11,12,],[1,-6,1,-3,-5,1,-4,-2,1,-7,-1,-8,]),'QUOTE':([0,1,2,3,4,5,6,8,9,10,11,12,],[2,-6,2,-3,-5,2,-4,-2,2,-7,-1,-8,]),'SYMBOL':([0,1,2,3,4,5,6,8,9,10,11,12,],[3,-6,3,-3,-5,3,-4,-2,3,-7,-1,-8,]),'FLOAT':([0,1,2,3,4,5,6,8,9,10,11,12,],[4,-6,4,-3,-5,4,-4,-2,4,-7,-1,-8,]),'LPAREN':([0,1,2,3,4,5,6,8,9,10,11,12,],[5,-6,5,-3,-5,5,-4,-2,5,-7,-1,-8,]),'INTEGER':([0,1,2,3,4,5,6,8,9,10,11,12,],[6,-6,6,-3,-5,6,-4,-2,6,-7,-1,-8,]),'$end':([1,3,4,6,7,8,11,],[-6,-3,-5,-4,0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'explist':([5,],[9,]),'expression':([0,2,5,9,],[7,8,10,12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN explist RPAREN','expression',3,'p_expression_fun','parser.py',64),
  ('expression -> QUOTE expression','expression',2,'p_expression_list','parser.py',72),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','parser.py',76),
  ('expression -> INTEGER','expression',1,'p_expression_integer','parser.py',80),
  ('expression -> FLOAT','expression',1,'p_expression_float','parser.py',84),
  ('expression -> STRING','expression',1,'p_expression_string','parser.py',88),
  ('explist -> expression','explist',1,'p_explist','parser.py',96),
  ('explist -> explist expression','explist',2,'p_explist','parser.py',97),
]
